---
- hosts: "{{ homeassistant_host }}"
  become: yes
  vars_files:
    - external_vars.yaml

  tasks:

  - name: Create and add {{ user }} to group 'homeassistant'
    ansible.builtin.user:
      name: "{{ user }}" 
      group: homeassistant,sudo

  - name: Generate SSH key for {{ user }} 
    ansible.builtin.user:
      name: "{{ user }}" 
      generate_ssh_key: yes

  - name: Change hostname to 'homeassistant'
    ansible.builtin.hostname:
      name: homeassistant
